image: flutter

pipelines:
  default:
    - step:
        name: Install Flutter SDK
        script:
          - apt-get update
          - apt-get install -y unzip
          - curl https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v3.3.10-stable.tar.xz -o flutter.tar.xz
          - tar xf flutter.tar.xz
          - export PATH=`pwd`/flutter/bin:$PATH
        services:
          - docker
    - step:
        name: Get Flutter dependencies
        script:
          - flutter pub get
    - step:
        name: analyze
        script:
          - flutter run dart_code_metrics:metrics lib -r checkstyle > checkstyle-result.xml
        after-script:
          - pipe: atlassian/checkstyle-report:0.3.1
