image: dart
# PIPELINE PARA RODAR SOMENTE QUANDO FOR PULL REQUEST PARA A MASTER
pipelines:
  pull-requests:
    '**':
      - step:
          name: Dart Code Metrics
          script:
          - if [ "$BITBUCKET_BRANCH" == "master" ]; then dart pub global activate Dart_code_metrics; fi
          - if [ "$BITBUCKET_BRANCH" == "master" ]; then dart pub global run dart_code_metrics:metrics analyze --fatal-style --fatal-performance --fatal-warnings --reporter=checkstyle lib; fi
          after-script:
          - if [ "$BITBUCKET_BRANCH" == "master" ]; then atlassian/checkstyle-report:0.3.1; fi
          artifacts:
          -  if [ "$BITBUCKET_BRANCH" == "master" ]; then checkstyle.xml; fi
      
          
