image: dart
# PIPELINE PARA RODAR SOMENTE QUANDO FOR PULL REQUEST PARA A MASTER
pipelines:
  pull-requests:
    '**':
      - step:
          name: Dart Code Metrics
          script:
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == "master" ]; then dart pub global activate dart_code_metrics; fi
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == "master" ]; then dart pub global run dart_code_metrics:metrics analyze --fatal-style --fatal-performance --fatal-warnings --reporter=checkstyle lib > checkstyle-result.xml; fi || exit 0 
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == "master" ]; then dart run dart_code_metrics:metrics analyze lib -r html; fi
          artifacts:
                 - metrics/**
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.1
      
       