image: dart

pipelines:
  default:
    - step:
        name: analyze
        script:
         - if [ "$BITBUCKET_BRANCH" == "master" ]; then dart pub global activate dart_code_metrics; fi
         - if [ "$BITBUCKET_BRANCH" == "master" ]; then dart pub global run dart_code_metrics:metrics analyze --fatal-style --fatal-performance --fatal-warnings --reporter=checkstyle lib; fi
        after-script:
          - if [ "$BITBUCKET_BRANCH" == "master" ]; then atlassian/checkstyle-report:0.3.1; fi 
        artifacts:
          - if [ "$BITBUCKET_BRANCH" == "master" ]; then checkstyle.xml; fi
          
