workflows:
  pr-development-android:
    name: PR metrics
    instance_type: mac_pro
    max_build_duration: 20
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "master"
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - echo 'previous step'
      - name: Dart Code Metrics
        script: |
          mkdir -p metrics-results
          flutter pub run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json
        test_report: metrics-results/dart_code_metrics.json 